### ISSUE TITLE
costume button

### ISSUE THREAD

**Issue by dipanjanpanja6** [checkr/react-github-login#25]
nstead of custom css class, It will be great if you can make custom component for the button.

For example if I want to use material-ui button I can extend it easily.

**Comment by DanteRangel** [comment]
> nstead of custom css class, It will be great if you can make custom component for the button.
> 
> For example if I want to use material-ui button I can extend it easily.

maybe you could use `children=` for instance:
```
<GitHubLogin 
            clientId="123123123123"
            onSuccess={someMethod}
            onFailure={someMethod}
            redirectUri=""
            scope="user,public_repo"
            children={this.label(provider, faGithubSquare)}
            className={"waves-effect waves-light btn social " + provider.name}
          />
```
In `className` you can put the materialize class and if you need that the button contain the icon would be...
```
label = (provider, icon) => {
    return (
      <React.Fragment>
        <i className="left"><FontAwesomeIcon icon={icon} size="1x" /></i>
        {"Ingresa con " + provider.description}
      </React.Fragment>
    );
  }
```

<img width="549" alt="Captura de Pantalla 2020-06-14 a la(s) 0 11 45" src="https://user-images.githubusercontent.com/22134423/84585272-ae2b4f00-add3-11ea-8dc4-743c2a7a2e44.png">
